# ---
# services:
#   nebula-sync:
#     image: ghcr.io/lovelaze/nebula-sync:latest
#     container_name: nebula-sync
#     environment:
#       - PRIMARY=${PRIMARY}
#       - REPLICAS=${REPLICAS}
#       - FULL_SYNC=true
#       - SYNC_CONFIG_NTP=true
#       - CRON=0 * * * *
#     restart: unless-stopped
# networks: {}

services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    network_mode: host
    environment:
      - PRIMARY=${PRIMARY}
      - REPLICAS=${REPLICAS}
      - FULL_SYNC=true
      - RUN_GRAVITY=false
      - CLIENT_TIMEOUT_SECONDS=60
      - CLIENT_RETRY_DELAY_SECONDS=3
      - SYNC_CONFIG_NTP=true
      - CRON=0 * * * *
      - API_ENABLED=false
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "nebula-sync", "--version"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s


