server {
    listen 443 ssl;
    http2 on;

    server_name nginx.sinq.cc;

    ssl_certificate     /etc/letsencrypt/live/sinq.cc/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sinq.cc/privkey.pem;

    # Opcjonalnie BasicAuth:
    # auth_basic "Restricted - nginx.sinq.cc";
    # auth_basic_user_file /etc/nginx/secrets/nginx-ui.htpasswd;

    resolver 127.0.0.11 valid=30s ipv6=off;
    set $nginx_ui_upstream "nginx-ui:9000";

    location / {
        proxy_pass http://$nginx_ui_upstream;

        proxy_set_header Host               $host;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  https;
        proxy_set_header X-Forwarded-Host   $host;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
