server {
    listen 80;
    server_name prometheus.sinq.cc;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name prometheus.sinq.cc;

    ssl_certificate     /etc/letsencrypt/live/prometheus_grafana/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/prometheus_grafana/privkey.pem;

    location / {
        proxy_pass http://prometheus:9090;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}