services:
  uptime-kuma:
    image: louislam/uptime-kuma:${UPTIME_KUMA_TAG}
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "${UPTIME_KUMA_PORT}:3001"
    volumes:
      - /opt/docker_volumes/uptimekuma:/app/data
    healthcheck:
      test: ["CMD", "extra/healthcheck"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 180s

networks:
  proxy_net:
    external: true
