services:
  rclone:
    image: rclone/rclone:latest
    container_name: rclone
    restart: unless-stopped

    command: >
      rcd
      --rc-addr=:${RCLONE_INTERNAL_PORT}
      --rc-no-auth
      --rc-web-gui
      --rc-web-gui-update
      --rc-web-gui-no-open-browser
      --rc-enable-metrics
      -vv

    environment:
      TZ: ${TZ}

    volumes:
      - ${RCLONE_CONFIG_PATH}:/config/rclone
      - ${RCLONE_DATA_PATH}:/data

    healthcheck:
      test: ["CMD", "rclone", "rc", "--rc-addr=127.0.0.1:${RCLONE_INTERNAL_PORT}", "--timeout=5s", "core/version"]
      interval: 30s
      timeout: 7s
      retries: 5
      start_period: 30s

    networks:
      - proxy_net

networks:
  proxy_net:
    external: true